name: figure1cyarn
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
  - anaconda
dependencies:
  - r-base=3.6.2
  - r-devtools
  - conda-forge::r-readr
  - conda-forge::r-biocmanager
  - conda-forge::r-downloader
  - bioconda::bioconductor-yarn
  - bioconda::bioconductor-edger
  - bioconda::bioconductor-biomart
  - conda-forge::r-dbi=1.1.0