name: figure1cyarn
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
  - anaconda
dependencies:
  - r-base=3.6.2
  - conda-forge::r-downloader=0.4
  - conda-forge::r-readr=1.3.1
  - bioconda::bioconductor-biomart=2.42.0