conda install -c bioconda bioconductor-edger -y
conda install -c conda-forge r-readr -y
conda install -c bioconda bioconductor-multtest -y
conda install -c conda-forge r-r.utils -y 
conda install -c conda-forge r-snakecase -y
conda install -c conda-forge r-statmod -y
conda install -c bioconda bioconductor-stan -y
conda install -c bioconda bioconductor-rtracklayer -y
conda install -c conda-forge r-reshape -y
conda install -c conda-forge r-pheatmap -y
conda install -c bioconda bioconductor-limma -y
conda install -c bioconda bioconductor-edger -y
conda install -c bioconda bioconductor-multtest -y
conda install -c conda-forge r-ggsci -y
conda install -c conda-forge r-rjags -y
conda install -c conda-forge r-compute.es -y
conda install -c conda-forge plotly -y
conda install -c bioconda r-pheatmap -y
conda install -c bioconda gffread -y
conda install -c bioconda bioconductor-biostrings -y
