name: figure1cyarn
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
  - anaconda
dependencies:
  - r-base=3.6.2
  - conda-forge::libgcc=7.2.0
  - r-devtools=2.0.2
  - r-stringr=1.4.0
  - r-stringi=1.4.3
  - conda-forge::zlib=1.2.11
  - conda-forge::r-downloader=0.4
  - conda-forge::r-readr=1.3.1
  - bioconda::bioconductor-biomart=2.42.0
